apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbox
spec:
  destination:
    namespace: netbox
    server: https://kubernetes.default.svc
  source:
    path: helm/netbox/chart
    repoURL: https://github.com/K4pper/svendeproeve
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  project: netbox
  syncPolicy:
    syncOptions:
      - CreateNamespace=true